<?php declare(strict_types=1);

use Drupal\Core\Session\AccountInterface;

function commerce_demo_graphql_install() {
  user_role_grant_permissions(AccountInterface::ANONYMOUS_ROLE, [
    'execute graphql requests',
    'execute persisted graphql requests'
  ]);
  user_role_grant_permissions(AccountInterface::AUTHENTICATED_ROLE, [
    'execute graphql requests',
    'execute persisted graphql requests'
  ]);
}
